import { productSlug, servicePages } from './data/seoContent';
export const defaultSiteUrl='https://www.vendorasystems.com';
const basePages={
 '/':['Custom Vending Machine Manufacturer | Vendora Systems','OEM and ODM vending machines customized for your products, branding, dispensing, cooling, payments and software.'],
 '/products':['Customizable Vending Machine Platforms | Vendora','Choose a commercial vending base model and customize capacity, dispensing, cooling, payments, connectivity and exterior branding.'],
 '/about':['About Vendora Systems','Custom vending hardware and connected retail development for brands, operators and professional unattended retail.'],
 '/news-blog/':['Vending Operator Resources | Vendora','Practical guidance for vending location planning, assortment, restocking, payments and fleet uptime.'],
 '/faq':['Smart Vending Machine FAQ | Vendora','Answers about machine options, payments, telemetry, installation, lead times, warranty and service.'],
 '/contact':['Request a Custom Vending Machine Quote | Vendora','Tell Vendora about your product, branding, dispensing, payment, software and production requirements.'],
 '/privacy':['Privacy Policy | Vendora Systems','How Vendora Systems collects, uses and protects business contact information.'],
 '/terms':['Terms of Use | Vendora Systems','Terms governing use of the Vendora Systems website.'],
 '/privacy-choices':['Privacy Choices | Vendora Systems','Manage optional analytics for the Vendora Systems website.'],
 '/privacy-request':['Privacy Request | Vendora Systems','Submit a request concerning your personal information.']
};
const privatePages={'/login':['Account Sign In | Vendora Systems','Sign in to manage machine quotes and conversations.'],'/quote':['Machine Quote List | Vendora Systems','Build a private vending machine quote list.'],'/admin':['Fleet Admin | Vendora Systems','Private vending platform administration.'],'/admin/users':['User Admin | Vendora Systems','Private user administration.'],'/admin/roles':['Role Admin | Vendora Systems','Private role administration.'],'/admin/articles':['Resources Admin | Vendora Systems','Private editorial workspace.'],'/admin/faqs':['FAQ Admin | Vendora Systems','Private FAQ workspace.'],'/admin/privacy':['Privacy Admin | Vendora Systems','Private privacy workspace.'],'/support/inbox':['Support Inbox | Vendora Systems','Private customer support workspace.']};
export function buildPublicSeoPaths(products=[],articles=[]){return [...Object.keys(basePages),...Object.keys(servicePages).map(slug=>`/services/${slug}`),...products.map(p=>`/products/${productSlug(p)}`),...articles.filter(a=>a.status==='published').map(a=>`/news-blog/${a.slug}`)]}
export function buildPrerenderPaths(products=[],articles=[]){return [...new Set([...buildPublicSeoPaths(products,articles),...Object.keys(privatePages),'/404'])]}
export function normalizeSeoPath(pathname='/'){if(!pathname)return '/';const clean=pathname.split('?')[0].replace(/\/{2,}/g,'/');if(clean==='/news-blog')return '/news-blog/';return clean.length>1?clean.replace(/\/$/,''):clean}
export function getSeoForPath(pathname='/',products=[],articles=[]){const path=normalizeSeoPath(pathname);const defaults={path,canonical:path,image:'/vending/hero-vending-machine.png',type:'website',noindex:false};if(basePages[path])return {...defaults,title:basePages[path][0],description:basePages[path][1],schemaType:path==='/'||path==='/about'?'organization':'webpage'};if(privatePages[path])return {...defaults,title:privatePages[path][0],description:privatePages[path][1],noindex:true};const pm=path.match(/^\/products\/(.+)$/);if(pm){const product=products.find(p=>productSlug(p)===pm[1]);if(product)return {...defaults,title:`${product.name} | Vendora Systems`,description:product.description,image:product.image,schemaType:'product',product}}const sm=path.match(/^\/services\/(.+)$/);if(sm&&servicePages[sm[1]]){const s=servicePages[sm[1]];return {...defaults,title:`${s.title} | Vendora Systems`,description:s.intro,image:s.image,schemaType:'webpage'}}const am=path.match(/^\/news-blog\/(.+)$/);if(am){const article=articles.find(a=>a.slug===am[1]);if(article)return {...defaults,title:`${article.title} | Vendora Systems`,description:article.summary,image:article.image||defaults.image,type:'article',schemaType:'article',article}}return {...defaults,title:'Page Not Found | Vendora Systems',description:'The requested page could not be found.',canonical:null,noindex:true}}
export function getStructuredData(seo,siteUrl=defaultSiteUrl,faqs=[]){const root=siteUrl.replace(/\/$/,'');const url=seo.canonical?`${root}${seo.canonical}`:root;const org={'@type':'Organization',name:'Vendora Systems',url:root,description:'A B2B supplier of smart commercial vending machines and connected unattended retail systems.',knowsAbout:['Vending machines','Unattended retail','Cashless payments','Remote inventory monitoring','Commercial refrigeration','Vending operations']};if(seo.path==='/faq')return {'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))};if(seo.schemaType==='organization')return {'@context':'https://schema.org',...org};if(seo.schemaType==='product'&&seo.product)return {'@context':'https://schema.org','@type':'Product',name:seo.product.name,description:seo.product.description,image:`${root}${seo.product.image}`,sku:seo.product.id,category:seo.product.category,url,audience:{'@type':'BusinessAudience',audienceType:'Vending operators, workplaces, campuses, healthcare facilities and property managers'},additionalProperty:[{'@type':'PropertyValue',name:'Capacity',value:seo.product.inci},{'@type':'PropertyValue',name:'Best for',value:seo.product.recommendedUse},{'@type':'PropertyValue',name:'Temperature',value:seo.product.solubility},{'@type':'PropertyValue',name:'Dimensions',value:seo.product.sizes},{'@type':'PropertyValue',name:'Typical MOQ',value:seo.product.moq},{'@type':'PropertyValue',name:'Typical lead time',value:seo.product.leadTime}]};return {'@context':'https://schema.org','@type':'WebPage',name:seo.title,description:seo.description,url}}
