import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Building2, CheckCircle2, Mail, Send } from 'lucide-react';
import wsClient from '../api/ws';

const initial=product=>({name:'',company:'',country:'United States',email:'',whatsapp:'',businessType:'operator',salesChannels:'',websiteUrl:'',targetRetailPrice:'',annualVolume:'',productCategory:'snack-drink',specifications:product,estimatedQuantity:'',deliveryDestination:'',targetDelivery:'',message:'',website:''});
export function QuoteForm({initialProduct='',compact=false}){
  const [form,setForm]=useState(()=>initial(initialProduct)); const [status,setStatus]=useState({sending:false,error:'',reference:''});
  useEffect(()=>{if(initialProduct)setForm(x=>({...x,specifications:initialProduct}))},[initialProduct]); const update=e=>setForm(x=>({...x,[e.target.name]:e.target.value}));
  const submit=async e=>{e.preventDefault();setStatus({sending:true,error:'',reference:''});try{const res=await fetch('/api/quotes/public',{method:'POST',headers:{'Content-Type':'application/json','X-Visitor-Id':wsClient.getVisitorId()},body:JSON.stringify(form)});const result=await res.json();if(!res.ok)throw new Error(result.message||'Unable to submit inquiry');setStatus({sending:false,error:'',reference:result.data.reference});setForm(initial(''))}catch(err){setStatus({sending:false,error:err.message,reference:''})}};
  if(status.reference)return <div className="rounded-3xl bg-[#e4e8e1] p-8 text-center"><CheckCircle2 className="mx-auto text-[#d95f2b]" size={44}/><h2 className="mt-4 font-heading text-2xl font-bold">Your deployment inquiry is with us.</h2><p className="mt-2 text-[#5f6a62]">Our vending solutions team will follow up. Reference: <strong>{status.reference}</strong></p></div>;
  return <form onSubmit={submit} className={`grid gap-6 ${compact?'':'rounded-[2rem] bg-white p-6 shadow-sm sm:p-9'}`}>
    <input name="website" value={form.website} onChange={update} className="hidden" tabIndex="-1" autoComplete="off"/>
    <div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a05247]">1 · Contact</p><div className="mt-4 grid gap-5 sm:grid-cols-2">{[['name','Your name *','text'],['company','Company *','text'],['email','Business email *','email'],['whatsapp','Phone / WhatsApp','text'],['websiteUrl','Company website','url'],['country','Country *','text']].map(([name,label,type])=><label key={name}><span className="mb-2 block text-sm font-semibold">{label}</span><input required={['name','company','email','country'].includes(name)} type={type} name={name} value={form[name]} onChange={update} className="w-full rounded-xl border-[#2d201d]/15"/></label>)}</div></div>
    <div className="border-t border-[#2d201d]/10 pt-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a05247]">2 · Organization & demand</p><div className="mt-4 grid gap-5 sm:grid-cols-2">
      <label><span className="mb-2 block text-sm font-semibold">Organization type *</span><select required name="businessType" value={form.businessType} onChange={update} className="w-full rounded-xl border-[#17201c]/15"><option value="operator">Vending operator</option><option value="workplace">Office / workplace</option><option value="education">School / university</option><option value="healthcare">Healthcare facility</option><option value="property">Property manager</option><option value="distributor">Equipment distributor</option></select></label>
      <label><span className="mb-2 block text-sm font-semibold">Location type *</span><input required name="salesChannels" value={form.salesChannels} onChange={update} className="w-full rounded-xl border-[#17201c]/15" placeholder="e.g. office lobby, 500 daily users"/></label>
      <label><span className="mb-2 block text-sm font-semibold">Target investment</span><input name="targetRetailPrice" value={form.targetRetailPrice} onChange={update} className="w-full rounded-xl border-[#17201c]/15" placeholder="e.g. USD 8,000 per location"/></label>
      <label><span className="mb-2 block text-sm font-semibold">Planned locations</span><input name="annualVolume" value={form.annualVolume} onChange={update} className="w-full rounded-xl border-[#17201c]/15" placeholder="e.g. 12 machines across 8 sites"/></label>
    </div></div>
    <div className="border-t border-[#17201c]/10 pt-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d95f2b]">3 · Custom machine requirement</p><div className="mt-4 grid gap-5 sm:grid-cols-2">
      <label><span className="mb-2 block text-sm font-semibold">Machine category</span><select name="productCategory" value={form.productCategory} onChange={update} className="w-full rounded-xl border-[#17201c]/15"><option value="snack-drink">Snack & drink</option><option value="fresh-food">Fresh food</option><option value="specialty">Specialty retail</option><option value="locker">Smart locker</option><option value="unsure">Recommend a format</option></select></label>
      <label><span className="mb-2 block text-sm font-semibold">Estimated first order (units) *</span><input required type="number" min="1" name="estimatedQuantity" value={form.estimatedQuantity} onChange={update} className="w-full rounded-xl border-[#17201c]/15" placeholder="e.g. 4"/></label>
      <label><span className="mb-2 block text-sm font-semibold">Main customization focus</span><select name="deliveryDestination" value={form.deliveryDestination} onChange={update} className="w-full rounded-xl border-[#17201c]/15"><option value="">Select an option</option><option value="branding">Branding & exterior</option><option value="hardware">Cabinet & dispensing hardware</option><option value="payment">Payment & identity</option><option value="software">Software & system integration</option><option value="full-oem">Full OEM / ODM project</option></select></label>
      <label><span className="mb-2 block text-sm font-semibold">Target project timing</span><input name="targetDelivery" value={form.targetDelivery} onChange={update} className="w-full rounded-xl border-[#17201c]/15" placeholder="e.g. prototype in October"/></label>
    </div><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">Product and customization brief *</span><textarea name="specifications" required rows="5" value={form.specifications} onChange={update} className="w-full rounded-xl border-[#17201c]/15" placeholder="Include product dimensions and weight, capacity, temperature, dispensing method, payment, branding, screen UI and integration requirements."/></label><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">Site access, delivery destination and other notes</span><textarea name="message" rows="4" value={form.message} onChange={update} className="w-full rounded-xl border-[#17201c]/15" placeholder="e.g. ground-floor office lobby; Shanghai; custom orange wrap and illuminated logo"/></label></div>
    {status.error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{status.error}</p>}<button disabled={status.sending} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#17201c] px-7 py-4 font-semibold text-white hover:bg-[#d95f2b] disabled:opacity-50"><Send size={18}/>{status.sending?'Sending…':'Send deployment inquiry'}</button><label className="flex items-start gap-3 text-xs leading-5 text-[#5f6a62]"><input type="checkbox" required className="mt-1 rounded"/><span>I am authorized to submit this B2B inquiry. I acknowledge the <Link to="/privacy" target="_blank">Privacy Policy</Link> and <Link to="/terms" target="_blank">Terms of Use</Link>.</span></label>
  </form>;
}
export default function Contact(){const [params]=useSearchParams();return <div className="min-h-screen bg-[#f6f4ee] pt-24"><section className="bg-[#17201c] px-5 py-20 text-center text-white"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#f58a57]">Custom engineering · OEM / ODM · Production</p><h1 className="mt-4 font-heading text-5xl font-black">Tell us what your machine needs to do.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/65">Share your product, brand, dispensing, payment and software requirements so we can develop the right custom vending configuration.</p></section><main className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-[.65fr_1.35fr]"><aside><Building2 size={32} className="text-[#d95f2b]"/><h2 className="mt-5 font-heading text-2xl font-bold">A useful custom brief includes</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-[#5f6a62]">{['Product dimensions, weight and packaging','Capacity and dispensing method','Temperature and power requirements','Brand colors, graphics and screen UI','Payments, identity and system integrations','Prototype quantity, rollout and timing'].map(x=><li key={x}>— {x}</li>)}</ul><a className="mt-7 flex items-center gap-2 font-semibold text-[#d95f2b]" href="mailto:sales@vendorasystems.com"><Mail size={18}/>sales@vendorasystems.com</a></aside><QuoteForm initialProduct={params.get('product')||''}/></main></div>}
