import { Link } from 'react-router-dom';
import { ArrowRight, BarChart3, CreditCard, Palette, Settings2, ShieldCheck, Wrench } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { productSlug } from '../data/seoContent';

const capabilities = [
  [CreditCard, 'Pay any way', 'Tap, scan or swipe with integrated card, mobile wallet and QR payment support.'],
  [BarChart3, 'Know every shelf', 'Remote telemetry shows sales, stock levels, temperatures and machine status in real time.'],
  [Wrench, 'Built to keep selling', 'Commercial refrigeration, modular parts and nationwide service plans reduce downtime.'],
  [ShieldCheck, 'Secure by design', 'Hardened enclosures, monitored access and dependable payment security for unattended retail.'],
];

export default function HomePage() {
  const { state } = useStore();
  const featured = [...state.products.slice(0, 3), ...state.products.slice(-3)];
  return <div className="min-h-screen bg-[#f6f4ee] pt-24">
    <section className="relative min-h-[720px] overflow-hidden bg-[#dfe4de]">
      <img src="/vending/hero-vending-machine.png" alt="A real smart vending machine installed in a modern office lobby" className="absolute inset-0 h-full w-full object-cover object-[65%_center]" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#f6f4ee]/98 via-[#f6f4ee]/82 to-transparent" />
      <div className="relative mx-auto flex min-h-[720px] max-w-7xl items-center px-5 sm:px-8"><div className="max-w-2xl py-20">
        <p className="mb-5 text-xs font-bold uppercase tracking-[.28em] text-[#d95f2b]">Custom vending · Built for your business</p>
        <h1 className="font-heading text-5xl font-black leading-[1.01] text-[#17201c] sm:text-7xl">Your products.<br/><span className="font-serif italic font-medium text-[#d95f2b]">Your machine.</span></h1>
        <p className="mt-7 max-w-xl text-lg leading-8 text-[#566159]">We customize the cabinet, shelves, cooling, payment hardware, software and exterior branding around your products, location and operating model.</p>
        <div className="mt-9 flex flex-wrap gap-3"><Link to="/products" className="inline-flex items-center gap-2 rounded-full bg-[#17201c] px-7 py-4 font-semibold text-white">Choose a base model <ArrowRight size={18}/></Link><Link to="/contact" className="rounded-full border border-[#17201c]/20 bg-white/80 px-7 py-4 font-semibold text-[#17201c] backdrop-blur">Start a custom project</Link></div>
        <div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[#667168]"><span>Custom cabinet & wrap</span><span>Flexible product channels</span><span>Custom software & payments</span></div>
      </div></div>
    </section>
    <section className="border-y border-white/5 bg-[#17201c] text-white"><div className="mx-auto grid max-w-7xl gap-px md:grid-cols-4">{capabilities.map(([Icon,title,desc])=><div key={title} className="flex gap-4 border-white/10 p-7 md:border-r"><Icon className="shrink-0 text-[#f58a57]"/><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm leading-6 text-white/60">{desc}</p></div></div>)}</div></section>
    <section className="bg-white py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#d95f2b]">Made to specification</p><h2 className="mt-3 font-heading text-4xl font-black text-[#17201c] sm:text-5xl">A platform you can make your own.</h2><p className="mt-5 text-lg leading-8 text-[#667168]">Start with a proven commercial chassis, then configure the customer experience and operating system around your requirements.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[Palette,'Brand & exterior','Custom colors, full-body graphics, illuminated logos, fascia panels and screen content.'],[Settings2,'Cabinet & dispensing','Machine dimensions, shelf pitch, spirals, conveyors, lockers and elevator delivery.'],[CreditCard,'Payment & identity','Card, mobile wallet, QR, cash, employee badge, membership and age verification.'],[BarChart3,'Software & integration','Custom UI, telemetry, ERP/API integration, promotions and operator reporting.']].map(([Icon,title,body])=><div key={title} className="rounded-3xl border border-[#17201c]/10 bg-[#f6f4ee] p-7"><Icon className="text-[#d95f2b]"/><h3 className="mt-5 text-xl font-bold text-[#17201c]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#667168]">{body}</p></div>)}</div><Link to="/services/formulation-support" className="mt-9 inline-flex items-center gap-2 font-semibold text-[#c44d1d]">See the customization process <ArrowRight size={17}/></Link></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#d95f2b]">Machine lineup</p><h2 className="mt-3 font-heading text-4xl font-black text-[#17201c] sm:text-5xl">The right machine for every stop.</h2><p className="mt-4 max-w-2xl leading-7 text-[#667168]">Compare capacity, cooling, payment options, dimensions and connectivity before building your deployment plan.</p></div><Link to="/products" className="inline-flex items-center gap-2 font-semibold text-[#c44d1d]">View all machines <ArrowRight size={17}/></Link></div>
      <div className="mt-11 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{featured.map((product)=><Link key={product.id} to={`/products/${productSlug(product)}`} className="group"><div className="relative overflow-hidden rounded-[2rem] bg-[#dfe4de]"><img src={product.image} alt={`${product.name} in a real-world installation`} className="aspect-[4/5] w-full object-cover transition duration-700 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-[11px] font-bold uppercase tracking-wider text-[#bd481b]">{product.badge}</span></div><h3 className="mt-4 font-heading text-xl font-bold text-[#17201c]">{product.name}</h3><p className="mt-1 text-sm text-[#667168]">{product.inci} · {product.recommendedUse}</p></Link>)}</div>
    </section>
    <section className="bg-[#e4e8e1] py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-2"><img src="/vending/fresh-food-machine.png" alt="A real fresh food vending machine in a public lobby" className="aspect-[4/3] w-full rounded-[2.5rem] object-cover"/><div className="lg:pl-10"><BarChart3 className="text-[#d95f2b]" size={30}/><p className="mt-6 text-xs font-bold uppercase tracking-[.24em] text-[#d95f2b]">One connected platform</p><h2 className="mt-3 font-heading text-4xl font-black leading-tight text-[#17201c] sm:text-5xl">Operate the machine, not a spreadsheet.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#5f6a62]">Track stock, temperature, sales and service events from one dashboard. Use live data to plan restocking routes and keep every location earning.</p><Link to="/services/formulation-support" className="mt-8 inline-flex items-center gap-2 border-b border-[#17201c] pb-1 font-semibold">Explore deployment support <ArrowRight size={17}/></Link></div></div></section>
  </div>;
}
