import { useMemo, useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { categories } from '../data/products';
import ProductCard from '../components/ProductCard';

export default function Products(){
  const {state}=useStore(); const [category,setCategory]=useState('all'); const [query,setQuery]=useState('');
  const products=useMemo(()=>state.products.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.description} ${p.benefit||''}`.toLowerCase().includes(query.toLowerCase())),[state.products,category,query]);
  return <div className="min-h-screen bg-[#f6f4ee] pt-24"><section className="bg-[#dfe4de] px-5 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[.26em] text-[#d95f2b]">Custom vending platforms</p><h1 className="mt-4 font-heading text-5xl font-black text-[#17201c] sm:text-6xl">Choose a base. Customize everything else.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#5f6a62]">Compare proven machine formats, then customize capacity, dispensing, cooling, payments, software and exterior branding for your project.</p></section><main className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><div className="flex flex-col gap-5 border-b border-[#17201c]/10 pb-7 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${category===c.id?'bg-[#17201c] text-white':'border border-[#17201c]/15 bg-white text-[#425048] hover:border-[#d95f2b]'}`}>{c.name}</button>)}</div><label className="relative block min-w-[280px]"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#667168]" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by machine, location or feature" className="w-full rounded-full border-[#17201c]/15 bg-white py-3 pl-11 pr-4"/></label></div><div className="my-8 flex items-center justify-between"><p className="text-sm text-[#667168]">{products.length} customizable base models</p><span className="flex items-center gap-2 text-sm font-semibold"><SlidersHorizontal size={16}/> Filtered by format</span></div>{products.length?<div className="grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{products.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div>:<div className="py-24 text-center"><h2 className="font-heading text-2xl font-bold">Nothing matched that search</h2><p className="mt-2 text-[#667168]">Try another machine type, location or feature.</p></div>}<section className="mt-20 rounded-[2rem] bg-[#17201c] p-9 text-white sm:flex sm:items-center sm:justify-between"><div><h2 className="font-heading text-3xl font-bold">Need a machine built around your product?</h2><p className="mt-2 text-white/60">Share product dimensions, packaging, temperature, payment, branding and rollout needs for a custom configuration.</p></div><a href="/contact" className="mt-5 inline-block rounded-full bg-white px-6 py-3 font-semibold text-[#17201c] sm:mt-0">Start a custom project</a></section></main></div>;
}
