import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Menu, X, UserRound, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useStore } from '../context/StoreContext';

export default function Header(){
  const [open,setOpen]=useState(false); const location=useLocation(); const {user}=useAuth(); const {state}=useStore(); const editCount=state.rfqAssortment.reduce((sum,item)=>sum+item.quantity,0);
  const nav=[['/products','Machines'],['/services/formulation-support','Deployment'],['/services/sampling-and-supply','Operations'],['/about','About'],['/news-blog/','Resources'],['/faq','FAQ']];
  return <><div className="fixed inset-x-0 top-0 z-[60] bg-[#17201c] py-2 text-center text-[10px] font-bold uppercase tracking-[.2em] text-white">Smart vending hardware · Cashless payments · Remote operations</div><header className="fixed inset-x-0 top-8 z-50 border-b border-black/10 bg-[#f6f4ee]/92 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/" className="font-heading text-2xl font-black tracking-[.06em] text-[#17201c]">VENDORA <span className="text-[10px] font-bold tracking-[.22em] text-[#d95f2b]">SYSTEMS</span></Link><nav className="hidden items-center gap-6 xl:flex">{nav.map(([path,label])=><Link key={path} to={path} className={`text-sm font-semibold ${location.pathname.startsWith(path)?'text-[#d95f2b]':'text-[#425048] hover:text-[#d95f2b]'}`}>{label}</Link>)}</nav><div className="flex items-center gap-1"><Link to="/contact" className="hidden rounded-full bg-[#d95f2b] px-4 py-2.5 text-sm font-semibold text-white md:block">Plan a deployment</Link><Link to="/login" aria-label={user?'Account':'Sign in'} className="rounded-full p-2 hover:bg-black/5"><UserRound size={19}/></Link><Link to="/quote" aria-label="Machine quote list" className="relative rounded-full p-2 hover:bg-black/5"><Sparkles size={19}/>{editCount>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-[#d95f2b] px-1 text-[10px] font-bold text-white">{editCount}</span>}</Link><button onClick={()=>setOpen(!open)} className="rounded-full p-2 xl:hidden" aria-label="Menu">{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="border-t bg-[#f6f4ee] px-5 py-5 xl:hidden">{nav.map(([path,label])=><Link onClick={()=>setOpen(false)} className="block py-3 font-semibold" key={path} to={path}>{label}</Link>)}<Link onClick={()=>setOpen(false)} to="/contact" className="mt-3 block rounded-full bg-[#d95f2b] px-5 py-3 text-center font-semibold text-white">Plan a deployment</Link></nav>}</header></>;
}
